#
# Copyright 2016-2026 Ghent University
#
# This file is part of vsc-utils,
# originally created by the HPC team of Ghent University (http://ugent.be/hpc/en),
# with support of Ghent University (http://ugent.be/hpc),
# the Flemish Supercomputer Centre (VSC) (https://www.vscentrum.be),
# the Flemish Research Foundation (FWO) (http://www.fwo.be/en)
# and the Department of Economy, Science and Innovation (EWI) (http://www.ewi-vlaanderen.be/en).
#
# https://github.com/hpcugent/vsc-utils
#
# All rights reserved.
#
"""
Checks that Jenkinsfile, tox.ini, ruff.toml, and GitHub Actions config
are in place and match what vsc-install would generate.
"""
import os
from pathlib import Path

import pytest

from vsc.install.ci import (
    JENKINSFILE,
    TOX_INI,
    GITHUB_ACTIONS,
    RUFF_TOML,
    gen_ruff_toml,
    gen_jenkinsfile,
    gen_tox_ini,
    gen_github_action,
    parse_vsc_ci_cfg,
    ENABLE_GITHUB_ACTIONS,
)


def _check_autogenerated(ci_cfg_fn, expected_contents):
    assert os.path.exists(ci_cfg_fn)
    current_contents = Path(ci_cfg_fn).read_text(encoding="utf8")

    ignore_fn = ci_cfg_fn + ".NOT_AUTOGENERATED_YET"
    if os.path.exists(ignore_fn):
        assert current_contents != expected_contents, (
            f"Found {ignore_fn}, so {ci_cfg_fn} was expected to differ from generated output"
        )
        txt = Path(ignore_fn).read_text(encoding="utf8")
        assert "github.com/hpcugent/vsc-install/issues/" in txt
    else:
        assert current_contents == expected_contents, (
            f"{ci_cfg_fn} doesn't match expected contents; "
            f"run 'python -m vsc.install.ci' to regenerate"
        )


def test_jenkinsfile():
    _check_autogenerated(JENKINSFILE, gen_jenkinsfile())


def test_tox_ini():
    _check_autogenerated(TOX_INI, gen_tox_ini())


def test_github_actions():
    vsc_ci_cfg = parse_vsc_ci_cfg()
    if not (os.path.exists(GITHUB_ACTIONS) or vsc_ci_cfg[ENABLE_GITHUB_ACTIONS]):
        pytest.skip("GitHub Actions not enabled")
    _check_autogenerated(GITHUB_ACTIONS, gen_github_action())


def test_ruff_toml():
    _check_autogenerated(RUFF_TOML, gen_ruff_toml())
